import { describe, expect, it } from "vitest";
import { computeForPersona } from "../compute";
import { buildSyncPayload } from "../upstreamSync";
import { PERSONAS } from "../../personas";
import type { Persona } from "../../types";
import {
  taxReducer,
  INITIAL_STATE,
  deriveTaxReturn,
  type SelfAssessmentPayment,
  type FactId,
  type TaxReturnState,
} from "../../../context/TaxReturnContext";

describe("Card 4 - Pay Tax Due & Challan 280 End-to-End Flow", () => {
  it("settles outstanding tax payable when Challan 280 is applied", () => {
    // 1. Initial State: Taxpayer with salary of 15,00,000 and TDS of 60,000 -> 37,500 Tax Due
    const salaryFact = {
      id: "fact-salary-1",
      kind: "salary" as const,
      label: "Salary from Employer",
      amount: 1_500_000,
      provenance: {
        reporter: "Employer",
        reporterKind: "employer" as const,
        identifier: "Form 16",
        filedOn: "2026-05-15",
        statement: "26AS" as const,
        onlyReporterCanFix: false,
      },
    };

    const initialTds = {
      id: "tds-1",
      label: "TDS on Salary",
      amount: 60_000,
      section: "192",
      provenance: {
        reporter: "Employer",
        reporterKind: "employer" as const,
        identifier: "Form 16",
        filedOn: "2026-05-15",
        statement: "26AS" as const,
        onlyReporterCanFix: false,
      },
    };

    const initialPersona: Persona = {
      ...PERSONAS.rakesh,
      facts: [salaryFact],
      taxPaid: [initialTds],
      claims: [],
    };

    const initialBreakdown = computeForPersona(initialPersona, "new");
    expect(initialBreakdown.refundOrDue).toBe(-37_500); // 37,500 tax due!

    const amountDue = Math.abs(initialBreakdown.refundOrDue);

    // 2. Simulate Challan 280 Payment generated by Card 4
    const payment: SelfAssessmentPayment = {
      bsrCode: "6001234",
      challanNo: "10042",
      amount: amountDue,
      date: "2026-07-25",
      majorHead: "0021",
      minorHead: "300",
      method: "UPI",
      bank: "State Bank of India (UPI Gateway)",
    };

    // 3. Apply Challan to Persona Ledger (what handleChallanPaid does)
    const paidEntry = {
      id: `sat-${payment.bsrCode}-${payment.challanNo}`,
      label: "Self-assessment tax paid (Challan 280)",
      amount: payment.amount,
      section: "140A",
      provenance: {
        reporter: "Self — Challan 280",
        reporterKind: "self" as const,
        identifier: `BSR ${payment.bsrCode} · serial ${payment.challanNo}`,
        filedOn: payment.date,
        statement: "self" as const,
        onlyReporterCanFix: false,
      },
    };

    const updatedPersona = {
      ...initialPersona,
      taxPaid: [...initialPersona.taxPaid, paidEntry],
    };

    // 4. Verify Ledger Computation: tax due is now completely cleared (settled to 0)
    const updatedBreakdown = computeForPersona(updatedPersona, "new");
    expect(updatedBreakdown.tdsCredits).toBe(initialBreakdown.tdsCredits + amountDue);
    expect(updatedBreakdown.refundOrDue).toBe(0); // Fully settled!

    // 5. Verify Bridge Sync: buildSyncPayload captures the 140A payment
    const syncPayload = buildSyncPayload({
      version: 2,
      lang: "en",
      personaId: "rakesh",
      baselinePersona: updatedPersona,
      persona: updatedPersona,
      corrections: [],
      confirmedFactIds: [paidEntry.id],
      regime: "new",
    });

    expect(syncPayload.selfAssessmentPayments).toHaveLength(1);
    expect(syncPayload.selfAssessmentPayments?.[0]).toMatchObject({
      bsrCode: "6001234",
      challanNo: "10042",
      amount: amountDue,
    });

    // 6. Verify Context Reducer: SYNC_STATE updates selfAssessmentPayments
    const contextStateAfterSync = taxReducer(INITIAL_STATE, {
      type: "SYNC_STATE",
      payload: syncPayload,
    });

    expect(contextStateAfterSync.selfAssessmentPayments).toHaveLength(1);

    // 7. Verify Context Derived Figures (what ITR-V Receipt and Dashboard display)
    const derived = deriveTaxReturn(contextStateAfterSync);
    expect(derived.selfAssessmentPaid).toBe(amountDue);
    expect(derived.isPayable).toBe(false);
    expect(derived.netPayable).toBe(0);
    expect(derived.isSettled).toBe(true);
  });
});
